feat(scenarios): add set_personal_meetings_time scenario
team-work-tools/team-work-telegram-bot pull request #91
Opened 2024-06-28 15:58 UTC by belyakova-anna

Closes #42

2024-06-29 21:19 UTC, deemp approved these changes

2024-06-29 21:24 UTC, deemp requested changes
Wait, I think this command should be called like `/set_personal_working_time`.

2024-06-29 21:52 UTC, belyakova-anna reviewed
command name is fixed

2024-06-30 08:47 UTC, deemp approved these changes

2024-06-30 08:48 UTC, deemp approved these changes

2024-06-30 08:48 UTC, merged